web-development COOKIE/SESSION
kojiyuu-123/basic_programming pull request #2
Opened 2020-05-20 02:37 UTC by kojiyuu-123

This pull request contains homework, in "web-development_COOKIE/SESSION".

To show my page correctly , please implement index.php in the top directory
( web_development_COOKIE_SESSION ).

Please check it.
Thank you.

2020-05-22 09:01 UTC, ohralathe requested changes
@kojiyuu-123 I checked and have some comments.

I don't know what homework you have done. so I just check some of them.

Next time, plz clarify out what you have done plz

2020-05-22 09:01 UTC, ohralathe commented on web_development_COOKIE_SESSION/src/courses/courses.js
> +function show_courses(){
@kojiyuu-123 for `JS`, use camel case plz

Next time, you should check the convention for each language before start.

2020-05-22 09:01 UTC, ohralathe commented on web_development_COOKIE_SESSION/src/helpers/route.php
> +class Route {
If not use, should remove it.

2020-05-22 09:01 UTC, ohralathe commented on web_development_COOKIE_SESSION/src/home/index.php
> +	    			echo ("placeholder='username'");
it is not `placeholder`. It's the value

2020-05-22 09:54 UTC, kojiyuu-123 commented on web_development_COOKIE_SESSION/src/courses/courses.js
> +function show_courses(){
Sorry, I'll change the code to camel case in javascript code.

2020-05-22 09:54 UTC, kojiyuu-123 commented on web_development_COOKIE_SESSION/src/helpers/route.php
> +class Route {
OK.

2020-05-26 08:21 UTC, ohralathe commented
@kojiyuu-123 good job.
thank you for update.

close this PR plz

2020-05-26 09:19 UTC, kojiyuu-123 commented
Thank you for your checking and comments

2020-05-26 09:19 UTC, closed without merging